-- Generated by nwg-displays on 2026-10-01 at 15:41:12. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.0",
    position = "1920x1440",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "2560x1440@59.95",
    position = "1920x0",
    scale = 1
})
hl.monitor({
    output = "DP-3",
    mode = "1920x1200@60.0",
    position = "0x744",
    scale = 1
})
